language: java

services:
  - docker

before_install:
  - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
  - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust
install:
  mvn --settings .maven.xml install -Dgpg.skip -Dmaven.javadoc.skip=true -B -V

script:
  - mvn --settings .maven.xml clean deploy -Prelease -B -U
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t inovus/gost-sign-service common-sign-service
  - docker images
  - docker tag common-sign-service inovus/gost-sign-service
  - docker push inovus/gost-sign-service