cxf:
  path: /
  jaxrs:
    component-scan: true
  servlet:
    init:
      service-list-path: /info
jaxrs:
  swagger:
    enabled: true
    title: Сервис подписи
    version: 1.9
    resource-package: ru.i_novus.common.sign.service.api.rest
sign:
  service:
    storage:
      type: file
      path: classpath:/ru/i_novus/common/sign/service/keys
      passwords:
        gost2012_256.pfx: 12345678
